### ISSUE TITLE
git push fails in version 2.30.2

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/git-os2#4]
An attempt to push a (small) change to a remote fails with something like this:
```
fatal: protocol error: bad line length character: ^603
fatal: bad revision '587755e5e80ef31d25665eb54c44da9d45704'
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
error: failed to push some refs to 'https://github.com/bitwiseworks/qtwebengine-os2.git'
```
The previous version (2.11.0) works w/o any changes anywhere.

**Comment by StevenLevine** [comment]
Based on the commits, I cannot tell if you picked up any of KO's 2.30.0 patches.  If not, perhaps it might be worthwhile to look at the .diff.

**Comment by dmik** [comment]
@StevenLevine no, I didn't pick up any of his patches yet. Most are not needed as we go a slightly different way in our porting. But some of his patches are surely worth learning, see e.g. #3. However, I don't see any push fixes there (https://github.com/komh/git-os2/commit/ee65749a8b180666db2edc1a76463f36db71b5d7 doesn't seem to be related).

The strange part with push is that `set GIT_TRACE=1` fixes it — commits push like a charm. This is a bit weird. Need to find why so. Another observation is that `bad revision` is actually the right one but with four first digits removed. No idea why that happens but may be related to LF/CRLF sh*t because it appears that revisions are read from stdin (need to check deeper).

**Comment by dmik** [comment]
I was right that it's a CRLF issue (of course). Deliberately switching stdout to O_BINARY in all git exes fixes the push problem. The current code does it conditionally, based on if `isatty()` returns FALSE. The logic is that if the standard input and output of the exe is connected to the console, we want O_TEXT because the OS/2 console needs CRLF. And of course if I do O_BINARY unconditionally, this breaks console output in a usual way (C strings end with LF and no CR so the cursor doesn't move to the beginning of the line).

I don't know why it worked before — perhaps because git was starting helper commands in a different way. Now `git push` results into this:
```
23:59:10.220000 git.c:444               trace: built-in: git push
23:59:10.224000 run-command.c:672       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/bitwiseworks/sandbox.git
23:59:10.351000 git.c:730               trace: exec: git-remote-https origin https://github.com/bitwiseworks/sandbox.git
23:59:10.351000 run-command.c:672       trace: run_command: git-remote-https origin https://github.com/bitwiseworks/sandbox.git
23:59:10.755000 run-command.c:672       trace: run_command: 'git credential-store get'
23:59:10.956000 git.c:444               trace: built-in: git credential-store get
23:59:11.198000 run-command.c:672       trace: run_command: 'git credential-store store'
23:59:11.327000 git.c:444               trace: built-in: git credential-store store
23:59:11.341000 run-command.c:672       trace: run_command: git send-pack --stateless-rpc --helper-status --thin --no-progress https://github.com/bitwiseworks/sandbox.git/ --stdin
23:59:11.466000 git.c:444               trace: built-in: git send-pack --stateless-rpc --helper-status --thin --no-progress https://github.com/bitwiseworks/sandbox.git/ --stdin
23:59:11.480000 run-command.c:672       trace: run_command: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset -q
23:59:11.609000 git.c:444               trace: built-in: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset -q
To https://github.com/bitwiseworks/sandbox.git
   89b384e..af0d5ff  master -> master
```
It's clearly seen that `pack-objects` writes the object data to STDOUT and `send-pack` reads it from STDIN. Most likely, `send-pack` starts a `pack-objects` child and redirects its STDOUT to its own STDIN to avoid temporary files. However, this does NOT cause `isatty` to return FALSE and hence O_BINARY is not set. This is a guess though, I need to check that.

**Comment by dmik** [comment]
No it seems I'm wrong about `isatty` above — it works like it should and returns 0 (FALSE) when the stream is redirected to a file or a socket. Fiddling with `setmode(O_BINARY)` appears to only help by accident. Perhaps, it's a racing issue of some sort. I will have to debug it further...

**Comment by dmik** [comment]
Okay, I guess I know what it is. Git now extensively starts child processes on secondary threads and since I switched from `fork` to `spawn2` this introduced a potential race when it comes to standard stream redirection -- if another child is started in the middle of this redirection, when file descriptors 0, 1, 2 are reassigned, it will ruin the both children's redirection. And this is what seems to happen here -- child processes get wrong streams and wrong data on them. And the racing nature of this problem explains why it is not always seen.

We have P_2_THREADSAFE in `spawn2` exactly to make this scenario thread-safe (by using an intermediate helper process) but somehow the way git uses it makes all the children stuck (waiting on one another I guess). I will look closer at that.

**Comment by dmik** [comment]
Double checking proved I was wrong about threads. Spawning is always done on thread 1 so no P_2_THREADSAFE is necessary. What I found a proof for though is that there is some problem with `spawn2` with relation to redirection even when P_2_THREADSAFE is not used. The proof is that switching from `spawn2` to a manual `spawnvpe` machinery (this is essentially what `spawn2` internally does and what https://github.com/komh/git-os2/commit/d1ac9665e49823463759da9ecea65e8acf7943fc does too) makes it work. I will look at `spawn2` then.

**Comment by dmik** [comment]
Some more details. Retrying the `spawn2` version several times makes it push (i.e. work). So it's a race anyway. However, I rechecked `spawn2` many times and couldn't find any visible flaw there that could explain this behavior. I actually even tried to replace it completely with the simple version like in KoMH's — still, it sometimes works and sometimes fails.

From what I see in the deep logs, the failure depends on the order in which child processes operate. There is quite a complex chain of processes. The main one and five chained children. And all exchange data using their stdin/stdout. Some of the children establishes an network connection and reads from a real IPv4 socket (i.e. from GitHub in this case) and feeds data to some stdin of some other child. And that other child sometimes reads an invalid length field. When it fails, this child kicks in little bit earlier. When it works, it gets its data a bit later.

I have no idea why changing the order of things leads to such a failure ATM. A much deeper debugging is needed. But there is a whole lot going on under the hood including Git RPC. It really sucks that this problem takes that much time.

It could work in earlier releases because we used fork and somehow this eliminated the failure, but that's just a guess. I will try to switch back to fork and see how stable it is.

Note that the new version from KoMH should also fail just like that though I couldn't catch it doing so. But that may be its specific timing somehow (no LIBCx `spawn2` overhead is involved in this case at all).

Totally weird problem and extremely hard to debug.

**Comment by dmik** [comment]
As I expected, switching back to `fork` makes the problem go away. This is really tricky. I will leave it with `fork` for the time being although I really don't like it being used here, it just wastes system resources.

**Comment by dmik** [comment]
I'm also trying `git pull` and sometimes some of the children in chain fails like this:
```
fatal: Put your home directory to the environment variable `HOME'
```
And given the absence of even UNIXROOT in the env, I must say it's pretty much empty. However, as I see in LIBCx logs, the respective call to `spawnve` gets a correct and complete environment argument. I'm really puzzled here. Might be some tricky kLIBC bug or even some Dos* bug. The environment doesn't look too extreme in terms of its size. A normal set of variables plus some GIT variables (like a dozen or so).

**Comment by dmik** [comment]
Re the last problem, it seems that it's caused by a LIBC `__spawnve` flaw and also by some Git bug which makes it corrupt the environment (to be found yet). By the time `spawn2` is called, the global `environ` array has this contents:
```c
"GIT_ALTERNATE_OBJECT_DIRECTORIES",
"GIT_CONFIG",
"GIT_OBJECT_DIRECTORY",
"GIT_DIR",
".",
"GIT_IMPLICIT_WORK_TREE",
"GIT_GRAFT_FILE",
"GIT_INDEX_FILE",
"GIT_NO_REPLACE_OBJECTS",
"GIT_REPLACE_REF_BASE",
"GIT_PREFIX",
"",
"GIT_SHALLOW_FILE",
"GIT_COMMON_DIR",
"AUTOSTART=PROGRAMS,TASKLIST..."
// all other normal OS/2 environment variables
```
I.e. we have both variables and their values registered as variables in the environment. This includes the GIT_PREFIX variable which has an empty value (which becomes an empty variable name). This causes `__spawnve` (which is a spawn work horse in kLIBC and also used by LIBCx `spawn2`) to truncate the environment passed to `DosExecPgm` and hence the above error message. I will create a LIBC ticket for that.

Note that it seems POSIX `putenv` or `setenv` doesn't put any restrictions on the contents of either the variable name or its value (except that `setenv` requires that the variable name should not contain an `=` character). So an empty variable name with an empty value is a valid case.

**Comment by dmik** [comment]
I guess I know what goes on with the environment variables above. Git interprets the environment strings like that in `start_command`:
```c
/**
 * To modify the environment of the sub-process, specify an array of
 * string pointers (NULL terminated) in .env:
 *
 * - If the string is of the form "VAR=value", i.e. it contains '='
 *   the variable is added to the child process's environment.
 *
 * - If the string does not contain '=', it names an environment
 *   variable that will be removed from the child process's environment.
 *
 * If the .env member is NULL, `start_command` will point it at the
 * .env_array `strvec` (so you may use one or the other, but not both).
 * The memory in .env_array will be cleaned up automatically during
 * `finish_command` (or during `start_command` when it is unsuccessful).
 */
```
So, when the environment variable is given w/o an `=` character, it should be interpreted as a removal of the respective variable from the child's environment. But `spawn2` knows nothing about that convention so it passes it as is to `__spawnve` which in turn passes it down to `DosExecPgm` unchanged. Which is happy with that either, so it ends w/o `=` and value in the started child as well and so on. I guess I will have to fix `spawn2` to handle this situation the same way — i.e. remove the variable from the child's environment when starting it.

**Comment by dmik** [comment]
Looks like bitwiseworks/libc#100 and bitwiseworks/libc#102 fixed the `git push` problem. So it seems that the order of things was out of sync because of the environment variable mess. Cannot reproduce this any more. Closing.
