### ISSUE TITLE
git 2.30.2: install/deinstall dependencies do not match

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/git-os2#8]
When I select "git" for installation, then "git-core", "git-core-doc" and "git-perl" are also installed as dependencies.
When I select "git" for deinstallation, then only "git-perl" is deinstalled as a dependency. I then need to select "git-core" for deinstallation which in turn will also deinstall "git-core-doc" as a dependency.

That does not seem to make much sense. I have not tried all that for git 2.11.0.

**Comment by SilvanScherrer** [comment]
this makes perfect sense. As git-core can be installed alone. and git-core requires git-core-doc. but git itself needs git-core as well. so it adds it as req for installation. but why should it deinstall everything? it might be you just want to deinstall the additional files and not the core.
